server:
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix: ""
      file-date-format: ""

verifiedaccess:
  googleCredentialsFile: "client-secrets.json"
