server:
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix: ""
      file-date-format: ""

authenticate:
  googleCredentialsFile: "google-client-secrets.json"

files:
  dir: "./files"
